In [1]:
sentences = []

In [2]:
with open('sentences.txt') as file:
    for line in file:
        sentences.append(line.lower())

In [3]:
words = []

In [4]:
sent_dict = {}

In [5]:
import re

In [6]:
count = 0
for sent in sentences:
    tmp_list = []
    for i in re.split('[^a-z]', sent):
        if i != '':
            tmp_list.append(i)
            words.append(i)
    sent_dict[count] = tmp_list
    count += 1

In [7]:
print(sent_dict)

{0: ['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process'], 1: ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes'], 2: ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output'], 3: ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals'], 4: ['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin'], 5: ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'd

In [8]:
word_dict = {}

In [9]:
count = 0
for i in set(words):
    word_dict[count] = i
    count +=1

In [10]:
print(word_dict)

{0: 'symbols', 1: 'enhancements', 2: 'major', 3: 'mavericks', 4: 'ancestor', 5: 'people', 6: 'tiger', 7: 'the', 8: 'osx', 9: 'july', 10: 'information', 11: 'an', 12: 'according', 13: 'online', 14: 'be', 15: 'also', 16: 'command', 17: 'fifth', 18: 'domestic', 19: 'learned', 20: 'during', 21: 'tamed', 22: 'running', 23: 'common', 24: 'was', 25: 'catenates', 26: 'create', 27: 'over', 28: 'cats', 29: 'symbol', 30: 'most', 31: 'undergone', 32: 'those', 33: 'domesticated', 34: 'genus', 35: 'store', 36: 'binary', 37: 'typically', 38: 'comparison', 39: 'process', 40: 'clear', 41: 'linux', 42: 'may', 43: 'type', 44: 'switch', 45: 'so', 46: 'closest', 47: 'too', 48: 'domestication', 49: 'needing', 50: 'just', 51: 'hear', 52: 'released', 53: 'named', 54: 'no', 55: 'that', 56: 'from', 57: 'similar', 58: 'upgrade', 59: 'won', 60: 'time', 61: 'weighing', 62: 'since', 63: 'firmware', 64: 'in', 65: 'marks', 66: 'wrong', 67: 'rather', 68: 'often', 69: 'small', 70: 'useful', 71: 'mountain', 72: 'increme

In [11]:
import numpy as np

In [12]:
a = np.zeros((len(sent_dict), len(word_dict)))

In [13]:
a.shape

(22, 254)

In [14]:
print(a)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
for i in sent_dict:
    for j in word_dict:
        if word_dict[j] in sent_dict[i]:
            a[i, j] += sent_dict[i].count(word_dict[j])

In [16]:
print(a[:, :22])

[[0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.

In [17]:
from scipy.spatial.distance import cosine

In [18]:
help(cosine)

Help on function cosine in module scipy.spatial.distance:

cosine(u, v, w=None)
    Compute the Cosine distance between 1-D arrays.
    
    The Cosine distance between `u` and `v`, is defined as
    
    .. math::
    
        1 - \frac{u \cdot v}
                  {||u||_2 ||v||_2}.
    
    where :math:`u \cdot v` is the dot product of :math:`u` and
    :math:`v`.
    
    Parameters
    ----------
    u : (N,) array_like
        Input array.
    v : (N,) array_like
        Input array.
    w : (N,) array_like, optional
        The weights for each value in `u` and `v`. Default is None,
        which gives each value a weight of 1.0
    
    Returns
    -------
    cosine : double
        The Cosine distance between vectors `u` and `v`.
    
    Examples
    --------
    >>> from scipy.spatial import distance
    >>> distance.cosine([1, 0, 0], [0, 1, 0])
    1.0
    >>> distance.cosine([100, 0, 0], [0, 1, 0])
    1.0
    >>> distance.cosine([1, 1, 0], [0, 1, 0])
    0.29289321881345

In [19]:
cos_dists = {}

In [20]:
for i in range(1, a.shape[0]):
    # cos_dists[i] = (cosine(a[0, :], a[i, :]))
    cos_dists[cosine(a[0, :], a[i, :])] = i

In [21]:
print(cos_dists)

{0.9527544408738466: 1, 0.8644738145642124: 2, 0.8951715163278082: 3, 0.7770887149698589: 4, 0.9402385695332803: 5, 0.7327387580875756: 6, 0.9258750683338899: 7, 0.8842724875284311: 8, 0.9055088817476932: 9, 0.8328165362273942: 10, 0.8804771390665607: 11, 0.8396432548525454: 12, 0.8703592552895671: 13, 0.8740118423302576: 14, 0.9442721787424647: 18, 0.8406361854220809: 16, 0.956644501523794: 17, 0.8885443574849294: 19, 0.8427572744917122: 20, 0.8250364469440588: 21}


In [22]:
print(cos_dists[sorted(cos_dists)[1]], cos_dists[sorted(cos_dists)[0]])

4 6
