In [1]:
from sklearn import datasets, model_selection, naive_bayes
import numpy as np

In [2]:
digits = datasets.load_digits()
breast_cancer = datasets.load_breast_cancer()

In [21]:
print(breast_cancer.data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [22]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [10]:
bernoulli_clf = naive_bayes.BernoulliNB()

In [14]:
digit_bern_score = model_selection.cross_val_score(bernoulli_clf, digits.data, digits.target)
print(f'Качество digits на классификаторе BernoulliNB: {digit_bern_score.mean()}')
cancer_bern_score = model_selection.cross_val_score(bernoulli_clf, breast_cancer.data, breast_cancer.target)
print(f'Качество breast_cancer на классификаторе BernoulliNB: {cancer_bern_score.mean()}')

Качество digits на классификаторе BernoulliNB: 0.8258236507780582
Качество breast_cancer на классификаторе BernoulliNB: 0.6274204028589994


In [15]:
multinom_clf = naive_bayes.MultinomialNB()

In [16]:
digit_multi_score = model_selection.cross_val_score(multinom_clf, digits.data, digits.target)
print(f'Качество digits на классификаторе MultinomialNB: {digit_multi_score.mean()}')
cancer_multi_score = model_selection.cross_val_score(multinom_clf, breast_cancer.data, breast_cancer.target)
print(f'Качество breast_cancer на классификаторе MultinomialNB: {cancer_multi_score.mean()}')

Качество digits на классификаторе MultinomialNB: 0.8708771489735053
Качество breast_cancer на классификаторе MultinomialNB: 0.8945790401930752


In [17]:
gauss_clf = naive_bayes.GaussianNB()

In [18]:
digit_gauss_score = model_selection.cross_val_score(gauss_clf, digits.data, digits.target)
print(f'Качество digits на классификаторе GaussianNB: {digit_gauss_score.mean()}')
cancer_gauss_score = model_selection.cross_val_score(gauss_clf, breast_cancer.data, breast_cancer.target)
print(f'Качество breast_cancer на классификаторе GaussianNB: {cancer_gauss_score.mean()}')

Качество digits на классификаторе GaussianNB: 0.8186003803550138
Качество breast_cancer на классификаторе GaussianNB: 0.9367492806089297


In [19]:
max(cancer_bern_score.mean(), cancer_multi_score.mean(), cancer_gauss_score.mean())

0.9367492806089297

In [20]:
max(digit_bern_score.mean(), digit_multi_score.mean(), digit_gauss_score.mean())

0.8708771489735053